services:
  - type: web
    name: testapp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: testapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: DAILY_USAGE_LIMIT
        value: 5
      - key: CORS_ORIGINS
        value: https://AwinlabNCHU.github.io/SlideAI,https://your-domain.com

databases:
  - name: testapp-db
    databaseName: testapp
    user: testapp_user
